In [8]:
import pandas as pd
import numpy as np
import seaborn as sns
from sklearn.preprocessing import MinMaxScaler, StandardScaler

In [9]:
df = pd.read_csv("student_data.csv")
print(df)

     StudentID                Name  Age  Gender  Class  Math  Science  \
0       S10000       Brianna Smith   16  Female     12    47       85
1       S10001      Rebecca Vargas   15    Male      8    40       94
2       S10002  Christopher Taylor   17    Male      7    71       59
3       S10003         Jared Riley   11  Female      7    72       78
4       S10004          Kevin Huff   14  Female     11    87       79
...        ...                 ...  ...     ...    ...   ...      ...
9995    S19995    Melissa Martinez   17  Female     10    66       48
9996    S19996       Sandy Bentley   13  Female      9    71       80
9997    S19997      Terry Campbell   14  Female      9    37       55
9998    S19998  Veronica Rasmussen   12  Female      8    87       42
9999    S19999      Kathleen Gates   15    Male      5    54       82

      English  History  Computer  AttendancePercent Extracurricular  Total  \
0          67       68        81              61.70             NaN    348
1          42       66        70              69.78           Drama    312
2          30       88        94              71.95           Music    342
3          32       38        92              81.31        Football    312
4          84       53        77              81.37             NaN    380
...       ...      ...       ...                ...             ...    ...
9995       81       54        49              66.44           Music    298
9996       40       76        75              66.37           Drama    342
9997       39       31        67              62.90          Debate    229
9998       33       37        36              66.59           Dance    235
9999       56       38        45              82.00        Football    275

     Grade
0        C
1        C
2        C
3        C
4        C
...    ...
9995     D
9996     C
9997     D
9998     D
9999     D

[10000 rows x 14 columns]

In [10]:
df.info()
df.describe(include="all")

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 10000 entries, 0 to 9999
Data columns (total 14 columns):
 #   Column             Non-Null Count  Dtype
---  ------             --------------  -----
 0   StudentID          10000 non-null  object
 1   Name               10000 non-null  object
 2   Age                10000 non-null  int64
 3   Gender             10000 non-null  object
 4   Class              10000 non-null  int64
 5   Math               10000 non-null  int64
 6   Science            10000 non-null  int64
 7   English            10000 non-null  int64
 8   History            10000 non-null  int64
 9   Computer           10000 non-null  int64
 10  AttendancePercent  10000 non-null  float64
 11  Extracurricular    8348 non-null   object
 12  Total              10000 non-null  int64
 13  Grade              10000 non-null  object
dtypes: float64(1), int64(8), object(5)
memory usage: 1.1+ MB

,StudentID,Name,Age,Gender,Class,Math,Science,English,History,Computer,AttendancePercent,Extracurricular,Total,Grade
count,10000,10000,10000.000000,10000,10000.000000,10000.000000,10000.000000,10000.0000,10000.000000,10000.000000,10000.000000,8348,10000.000000,10000
unique,10000,9360,NaN,2,NaN,NaN,NaN,NaN,NaN,NaN,NaN,5,NaN,5
top,S19983,Michael Smith,NaN,Female,NaN,NaN,NaN,NaN,NaN,NaN,NaN,Debate,NaN,C
freq,1,8,NaN,5090,NaN,NaN,NaN,NaN,NaN,NaN,NaN,1730,NaN,6377
mean,NaN,NaN,13.465000,NaN,8.470400,64.041900,64.570500,64.5288,64.332000,64.440600,79.876124,NaN,321.913800,NaN
std,NaN,NaN,2.278046,NaN,2.297358,20.192541,20.105682,20.1448,20.196761,20.218743,11.612209,NaN,45.283781,NaN
min,NaN,NaN,10.000000,NaN,5.000000,30.000000,30.000000,30.0000,30.000000,30.000000,60.000000,NaN,177.000000,NaN
25%,NaN,NaN,11.000000,NaN,6.000000,46.000000,47.000000,47.0000,47.000000,47.000000,69.710000,NaN,291.000000,NaN
50%,NaN,NaN,13.000000,NaN,8.000000,64.000000,65.000000,64.0000,64.000000,64.000000,79.995000,NaN,321.000000,NaN
75%,NaN,NaN,15.000000,NaN,10.000000,82.000000,82.000000,82.0000,82.000000,82.000000,89.830000,NaN,353.000000,NaN
max,NaN,NaN,17.000000,NaN,12.000000,99.000000,99.000000,99.0000,99.000000,99.000000,100.000000,NaN,475.000000,NaN

In [11]:
df.isnull().sum()

StudentID               0
Name                    0
Age                     0
Gender                  0
Class                   0
Math                    0
Science                 0
English                 0
History                 0
Computer                0
AttendancePercent       0
Extracurricular      1652
Total                   0
Grade                   0
dtype: int64

In [14]:
print(f"Mean of math_score: {df['Math'].mean()}")
print(f"Median of English_score: {df['English'].median()}")

Mean of math_score: 64.0419
Median of English_score: 64.0

In [15]:
dupli = df.duplicated()
print(dupli)

0       False
1       False
2       False
3       False
4       False
        ...
9995    False
9996    False
9997    False
9998    False
9999    False
Length: 10000, dtype: bool

In [16]:
df = df.drop_duplicates()
print(df)

     StudentID                Name  Age  Gender  Class  Math  Science  \
0       S10000       Brianna Smith   16  Female     12    47       85
1       S10001      Rebecca Vargas   15    Male      8    40       94
2       S10002  Christopher Taylor   17    Male      7    71       59
3       S10003         Jared Riley   11  Female      7    72       78
4       S10004          Kevin Huff   14  Female     11    87       79
...        ...                 ...  ...     ...    ...   ...      ...
9995    S19995    Melissa Martinez   17  Female     10    66       48
9996    S19996       Sandy Bentley   13  Female      9    71       80
9997    S19997      Terry Campbell   14  Female      9    37       55
9998    S19998  Veronica Rasmussen   12  Female      8    87       42
9999    S19999      Kathleen Gates   15    Male      5    54       82

      English  History  Computer  AttendancePercent Extracurricular  Total  \
0          67       68        81              61.70             NaN    348
1          42       66        70              69.78           Drama    312
2          30       88        94              71.95           Music    342
3          32       38        92              81.31        Football    312
4          84       53        77              81.37             NaN    380
...       ...      ...       ...                ...             ...    ...
9995       81       54        49              66.44           Music    298
9996       40       76        75              66.37           Drama    342
9997       39       31        67              62.90          Debate    229
9998       33       37        36              66.59           Dance    235
9999       56       38        45              82.00        Football    275

     Grade
0        C
1        C
2        C
3        C
4        C
...    ...
9995     D
9996     C
9997     D
9998     D
9999     D

[10000 rows x 14 columns]

In [18]:
df["Math"] = df["Math"].astype(int)
df["English"] = df["English"].round(1)
print(df.dtypes)

StudentID             object
Name                  object
Age                    int64
Gender                object
Class                  int64
Math                   int64
Science                int64
English                int64
History                int64
Computer               int64
AttendancePercent    float64
Extracurricular       object
Total                  int64
Grade                 object
dtype: object

In [20]:
minmax = MinMaxScaler()

df[["Math"]] = minmax.fit_transform(df[["Math"]])

print(df)

     StudentID                Name  Age  Gender  Class      Math  Science  \
0       S10000       Brianna Smith   16  Female     12  0.246377       85
1       S10001      Rebecca Vargas   15    Male      8  0.144928       94
2       S10002  Christopher Taylor   17    Male      7  0.594203       59
3       S10003         Jared Riley   11  Female      7  0.608696       78
4       S10004          Kevin Huff   14  Female     11  0.826087       79
...        ...                 ...  ...     ...    ...       ...      ...
9995    S19995    Melissa Martinez   17  Female     10  0.521739       48
9996    S19996       Sandy Bentley   13  Female      9  0.594203       80
9997    S19997      Terry Campbell   14  Female      9  0.101449       55
9998    S19998  Veronica Rasmussen   12  Female      8  0.826087       42
9999    S19999      Kathleen Gates   15    Male      5  0.347826       82

      English  History  Computer  AttendancePercent Extracurricular  Total  \
0          67       68        81              61.70             NaN    348
1          42       66        70              69.78           Drama    312
2          30       88        94              71.95           Music    342
3          32       38        92              81.31        Football    312
4          84       53        77              81.37             NaN    380
...       ...      ...       ...                ...             ...    ...
9995       81       54        49              66.44           Music    298
9996       40       76        75              66.37           Drama    342
9997       39       31        67              62.90          Debate    229
9998       33       37        36              66.59           Dance    235
9999       56       38        45              82.00        Football    275

     Grade
0        C
1        C
2        C
3        C
4        C
...    ...
9995     D
9996     C
9997     D
9998     D
9999     D

[10000 rows x 14 columns]

In [21]:
standard = StandardScaler()
df[["English"]] = standard.fit_transform(df[["English"]])
print(df)

     StudentID                Name  Age  Gender  Class      Math  Science  \
0       S10000       Brianna Smith   16  Female     12  0.246377       85
1       S10001      Rebecca Vargas   15    Male      8  0.144928       94
2       S10002  Christopher Taylor   17    Male      7  0.594203       59
3       S10003         Jared Riley   11  Female      7  0.608696       78
4       S10004          Kevin Huff   14  Female     11  0.826087       79
...        ...                 ...  ...     ...    ...       ...      ...
9995    S19995    Melissa Martinez   17  Female     10  0.521739       48
9996    S19996       Sandy Bentley   13  Female      9  0.594203       80
9997    S19997      Terry Campbell   14  Female      9  0.101449       55
9998    S19998  Veronica Rasmussen   12  Female      8  0.826087       42
9999    S19999      Kathleen Gates   15    Male      5  0.347826       82

       English  History  Computer  AttendancePercent Extracurricular  Total  \
0     0.122678       68        81              61.70             NaN    348
1    -1.118399       66        70              69.78           Drama    312
2    -1.714116       88        94              71.95           Music    342
3    -1.614830       38        92              81.31        Football    312
4     0.966610       53        77              81.37             NaN    380
...        ...      ...       ...                ...             ...    ...
9995  0.817681       54        49              66.44           Music    298
9996 -1.217685       76        75              66.37           Drama    342
9997 -1.267328       31        67              62.90          Debate    229
9998 -1.565187       37        36              66.59           Dance    235
9999 -0.423396       38        45              82.00        Football    275

     Grade
0        C
1        C
2        C
3        C
4        C
...    ...
9995     D
9996     C
9997     D
9998     D
9999     D

[10000 rows x 14 columns]

In [22]:
df.describe()
df.info()
print(df)

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 10000 entries, 0 to 9999
Data columns (total 14 columns):
 #   Column             Non-Null Count  Dtype
---  ------             --------------  -----
 0   StudentID          10000 non-null  object
 1   Name               10000 non-null  object
 2   Age                10000 non-null  int64
 3   Gender             10000 non-null  object
 4   Class              10000 non-null  int64
 5   Math               10000 non-null  float64
 6   Science            10000 non-null  int64
 7   English            10000 non-null  float64
 8   History            10000 non-null  int64
 9   Computer           10000 non-null  int64
 10  AttendancePercent  10000 non-null  float64
 11  Extracurricular    8348 non-null   object
 12  Total              10000 non-null  int64
 13  Grade              10000 non-null  object
dtypes: float64(3), int64(6), object(5)
memory usage: 1.1+ MB
     StudentID                Name  Age  Gender  Class      Math  Science  \
0       S10000       Brianna Smith   16  Female     12  0.246377       85
1       S10001      Rebecca Vargas   15    Male      8  0.144928       94
2       S10002  Christopher Taylor   17    Male      7  0.594203       59
3       S10003         Jared Riley   11  Female      7  0.608696       78
4       S10004          Kevin Huff   14  Female     11  0.826087       79
...        ...                 ...  ...     ...    ...       ...      ...
9995    S19995    Melissa Martinez   17  Female     10  0.521739       48
9996    S19996       Sandy Bentley   13  Female      9  0.594203       80
9997    S19997      Terry Campbell   14  Female      9  0.101449       55
9998    S19998  Veronica Rasmussen   12  Female      8  0.826087       42
9999    S19999      Kathleen Gates   15    Male      5  0.347826       82

       English  History  Computer  AttendancePercent Extracurricular  Total  \
0     0.122678       68        81              61.70             NaN    348
1    -1.118399       66        70              69.78           Drama    312
2    -1.714116       88        94              71.95           Music    342
3    -1.614830       38        92              81.31        Football    312
4     0.966610       53        77              81.37             NaN    380
...        ...      ...       ...                ...             ...    ...
9995  0.817681       54        49              66.44           Music    298
9996 -1.217685       76        75              66.37           Drama    342
9997 -1.267328       31        67              62.90          Debate    229
9998 -1.565187       37        36              66.59           Dance    235
9999 -0.423396       38        45              82.00        Football    275

     Grade
0        C
1        C
2        C
3        C
4        C
...    ...
9995     D
9996     C
9997     D
9998     D
9999     D

[10000 rows x 14 columns]